name: Docker Build and Render Deploy

on:
  push:
    branches:
      - feature/workflow-fix-3
      - dev

jobs:
  test:
    name: Run Next.js tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install sd
        run: cargo install sd
      - name: Inject Secrets into File
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          # Use 'sd' to find the placeholder and replace it with the env variable
          # The syntax is: sd 'find' 'replace' file_name
          
          # Replace the DATABASE_URL line
          sd 'postgres://\$\{DB_USER\}:\$\{DB_PASSWORD\}@\$\{DB_HOST\}:5432/\$\{DB_NAME\}' \
             "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}" \
             ./src/Dockerfile
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          target: production
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/projet-web:latest

      - name: Trigger Render API Deploy
        run: |
          curl --request POST \
            --url https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }} \
            --header 'accept: application/json' \
            --header 'authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
            --header 'content-type: application/json' \
            --data '{"clearCache": "clear"}'
